[build-system]
requires = [
    "setuptools>=46.1.0",
    "setuptools_scm[toml]>=5",
    "wheel",
    "setuptools_scm[toml]>=5.0.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# Configuration for setuptools_scm
version_scheme = "no-guess-dev"
local_scheme = "node-and-date"
